### ISSUE TITLE
[新主页] 添加SoftOSDev的主页

### ISSUE THREAD

**Issue by JingHai-Lingyun** [HomePlaza-Of-PCL2/Homepage-Market#1]
### 描述

链接：https://huaxihao.eu.org/desk/
作者：@SoftOSDev

### [可选]附件

*original posted at https://github.com/MFn233/PCL-Mainpage-Market/issues/13*

**Comment by JingHai-Lingyun** [comment]
@SoftOSDev 我需要一段主页介绍文案

**Comment by MFn233** [comment]
要不先close掉（

**Comment by JingHai-Lingyun** [comment]
太久了……
