### ISSUE TITLE
打开 Ad_closeNN 的 PCL2 主页 时报错

### ISSUE THREAD

**Issue by PhantomPixel-0418** [HomePlaza-Of-PCL2/Homepage-Market#11]
### 描述

打开 Ad_closeNN 的 PCL2 主页 时报错

### [可选]附件

[Log1.txt](https://github.com/user-attachments/files/17238047/Log1.txt)

**Comment by Ad-closeNN** [comment]
看起来像是链接 github pages 的问题？我把链接换成 gitcode 的吧...

**Comment by Ad-closeNN** [comment]
已解决。

**Comment by JingHai-Lingyun** [comment]
这不是 PCL 主页市场的问题，故 Close as Not Planned
