### ISSUE TITLE
[BUG] 奇怪的转义符号

### ISSUE THREAD

**Issue by MFn233** [HomePlaza-Of-PCL2/Homepage-Market#2]
### 描述

MD中的*在生成主页后会加一个转义符号\

### [可选]附件

![4da54f2095f89886fa4589681ab1feea](https://github.com/user-attachments/assets/fcca2ce5-e8e1-4f68-a52e-0a0e4ca2b078)

**Comment by JingHai-Lingyun** [comment]
Prettier 抽了……
